### PR TITLE
Added crash test 0506

### PR DESCRIPTION
**Pull request by Vihanakangas**
This is a bug found by fuzzing with spir-v shaders.

### CODE REVIEW

**Review by afd — CHANGES_REQUESTED** [review]
Three comments:

(1) I think we have a convention for tests added via spirv-fuzz, and I think it's to start the test name with spv - please look at existing tests in CTS; I think there are some .spv ones.

(2) I wonder if there's something we could do to make the diff intelligible to someone reading these tests. They're very hard to understand and review.

(3) In this case the diff is *huge*: it seems that loads of composites of an array type with 256 elements are added. Was the spirv-fuzz shrinker really not able to make this smaller? I fear this may be too pathological for a CTS test.

@paulthomson what do you think?

**Comment by Vihanakangas** [comment]
(1) It seems so yes. spv-stable-something seems to be the correct way of naming. The instructions I used had a different naming convention but I'll update that.

(2) I don't really know if there is anything that could be done. We could possibly comment out the parts of code that have been changed if someone doesn't want to use a diff tool. (Kind of encase them in a block so it's easier to notice.) Other than that, as you said, the tests are really hard to understand.

(3) I'm happy to abandon this one and find a simpler one if needed. Or do another fuzzing round if none of the existing ones are any simpler.

**Comment by paulthomson** [comment]
I checked it locally, like so:

```
cd bugs/PENDING_SUBMIT/0506-Pixel5-libllvmglnextso_00008f34d14d29b24549b833abd13872ae/reduced_1_result

# Compare reference and variant.
meld reference/1_spirv_asm/shader.frag.asm variant/1_spirv_asm/shader.frag.asm

# Compare variant_2 and variant.
meld variant_2/1_spirv_asm/shader.frag.asm variant/1_spirv_asm/shader.frag.asm
```

Yeah, it looks ridiculous. I think we should abandon this one. And maybe we should create a spirv-fuzz issue to try limit huge `OpCompositeConstruct`. 

Regarding (2): it must be particularly hard for dEQP reviewers, as they only see the AmberScript file. I can't see a way to get GitHub to compare files. Checking out PRs is easier than I thought though:

```
git fetch origin pull/80/head my_branch_name
```

**Comment by paulthomson** [comment]
I think we can close this.

**Pull request closed without merging**
