### PR TITLE
Move the tests submitted to CTS into PENDING_CTS

### PR DESCRIPTION
**Pull request by amakin-siru**

### CODE REVIEW

**Comment by amakin-siru** [comment]
It seems I messed up this PR since it includes unnecessary commits. I'll do a new PR with the right commit only.

**Review by afd — APPROVED** [review]

**Comment by afd** [comment]
Oh dear - sorry! I didn't read your comment until I reviewed and merged. Can you please do a PR with whatever is needed to resolve things (if anything)? But I squashed, so maybe all is well.

**Comment by afd** [comment]
@amakin-siru I have approved a bunch of other PRs but I won't merge them yet in case anything needs to be changed first in light of this PR. Please let me know and I will proceed to merge the other PRs when you give me the green light.

**Comment by amakin-siru** [comment]
I checked through the merged changes and fortunately everything seems to be correct. What happened here is that the PR included a commit which had already been merged but merging it twice didn't mess up anything. So, it's fine by me to proceed.

**Pull request merged**
